Comando !ja e !oc
devpt-org/welcome-bot pull request #41
Opened 2022-09-11 21:30 UTC by zorkpt

Adicionado comando !ja e !oc.

2022-09-12 20:10 UTC, IvoPereira requested changes
Deixei só algumas notas. Diz-me o que te parece!

Overall good job!

2022-09-12 20:10 UTC, IvoPereira commented on index.js
> +  if (messages.content === "!oc") messages.channel.send(oc);
Como temos frases fixas (e não uma construção dinâmica como no caso das entradas), diria que podemos remover os ficheiros de configuração das frases.

E sugeria talvez um switch aqui ao invés do if? Isto porque vejo que é bastante provável que o número de comandos aumente e conseguimos aumentar a legibilidade usando um switch.

2022-09-12 23:14 UTC, zorkpt commented on index.js
> +  if (messages.content === "!oc") messages.channel.send(oc);
Já fiz as alterações que falaste.
Tive também que adicionar á lista de intents o Intents.FLAGS.GUILD_MESSAGES.
Thanks! :)

2022-09-13 20:36 UTC, IvoPereira requested changes

2022-09-13 20:36 UTC, IvoPereira commented on index.js
> +    // no default
Podemos remover estas linhas ou temo-las atualmente por alguma razão?

Removendo-as diria que depois podemos dar merge.

2022-09-13 20:38 UTC, zorkpt commented on index.js
> +    // no default
Esse comentario fui obrigado a colocar para passar no eslint, mas vou retirar então

2022-09-13 20:39 UTC, IvoPereira commented on index.js
> +    // no default
Ah, estive agora a ver a regra. Está ok então! Vou dar merge.

2022-09-13 20:40 UTC, IvoPereira commented
Vou dar merge. Obrigado pela contribuição! :+1: 

Assim que fizer novo deploy deverá estar novo funcional.

2022-09-13 20:40 UTC, IvoPereira approved these changes

2022-09-13 20:40 UTC, merged