Adding some new lines :)
devpt-org/welcome-bot pull request #5
Opened 2021-11-30 16:33 UTC by 201flaviosilva

2021-12-09 20:32 UTC, IvoPereira requested changes

2021-12-09 20:32 UTC, IvoPereira commented on welcoming.txt
> +  , podes hacker o facebook por mim?
Sugeria alterar "hacker" por "hackear".

2021-12-09 20:32 UTC, IvoPereira commented on welcoming.txt
> +  , Olá Mundo.
Se a frase começa com uma vírgula, alteraria o olá para minúscula.

2021-12-10 17:23 UTC, 201flaviosilva commented on welcoming.txt
> +  , podes hacker o facebook por mim?
Sim tens razão faz mais sentido :)

2021-12-10 17:25 UTC, 201flaviosilva commented on welcoming.txt
> +  , Olá Mundo.
Yap, maus hábitos meus 😅

2022-04-29 17:03 UTC, merged